# Generated by Django 4.1.1 on 2022-10-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_remove_employee_hire_date_employee_empid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='empid',
        ),
    ]
