# Generated by Django 4.1.1 on 2022-10-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_remove_employee_empid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='location',
        ),
    ]
